version: '3.9'

services:
  mysql:
    image: mysql:9.2.0
    container_name: mysql
    ports:
        - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: one-menu
        MYSQL_USER: root
        MYSQL_PASSWORD: password