version: '3.9'

services:
  mysql:
    image: mysql:9.2.0
    container_name: mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: one-menu
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=password --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 5s
      retries: 40
      start_period: 10s
  app:
    image: one-menu:latest
    container_name: one-menu
    ports:
        - "8080:8080"
    environment:
        DB_HOST: mysql
        DB_PORT: 3306
        DB_USERNAME: root
        DB_PASSWORD: password
        DB_SCHEMA: one-menu
    depends_on:
      mysql:
        condition: service_healthy