version: '3.9'

services:
  mysql:
    image: mysql:9.2.0
    container_name: mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: one-menu